# Generated by Django 5.2 on 2025-06-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='datas',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='datas',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='datas',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='datas',
            name='Mail',
        ),
        migrations.AddField(
            model_name='datas',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datas',
            name='contact',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datas',
            name='mail',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
